# Generated by Django 3.2.9 on 2021-11-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articolo_contenuto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articolo',
            old_name='id_giornalista',
            new_name='giornalista',
        ),
    ]
